-- Create a new user SAMPATH_RAJKUMAR for the DA team
-- Co-authored with CoCo
use role accountadmin;
-- create users for DA team
CREATE OR REPLACE USER SAMPATH_RAJKUMAR
  PASSWORD = 'TempPass123!'
  DEFAULT_ROLE = 'OPENFLOW_ADMIN'
  DEFAULT_WAREHOUSE = 'DANDA_ALL'
  MUST_CHANGE_PASSWORD = TRUE;
-- Grant roles to the new user
GRANT ROLE OPENFLOW_ADMIN TO USER SAMPATH_RAJKUMAR;

CREATE OR REPLACE USER ANITHA_TIRUMALARAJU
  PASSWORD = 'TempPass123!'
  DEFAULT_ROLE = 'OPENFLOW_ADMIN'
  DEFAULT_WAREHOUSE = 'DANDA_ALL'
  MUST_CHANGE_PASSWORD = TRUE;
-- Grant roles to the new user
GRANT ROLE OPENFLOW_ADMIN TO USER ANITHA_TIRUMALARAJU;

CREATE OR REPLACE USER ASHWINI_SANKHE
  PASSWORD = 'TempPass123!'
  DEFAULT_ROLE = 'OPENFLOW_ADMIN'
  DEFAULT_WAREHOUSE = 'DANDA_ALL'
  MUST_CHANGE_PASSWORD = TRUE;
-- Grant roles to the new user
GRANT ROLE OPENFLOW_ADMIN TO USER ASHWINI_SANKHE;

CREATE OR REPLACE USER VIDHYA_VIJAYAKUMAR
  PASSWORD = 'TempPass123!'
  DEFAULT_ROLE = 'OPENFLOW_ADMIN'
  DEFAULT_WAREHOUSE = 'DANDA_ALL'
  MUST_CHANGE_PASSWORD = TRUE;
-- Grant roles to the new user
GRANT ROLE OPENFLOW_ADMIN TO USER VIDHYA_VIJAYAKUMAR;
